### ISSUE TITLE
Profile object isn't removed from all handles

### ISSUE THREAD

**Issue by eevee** [timbunce/Plack--Middleware--Debug--DBIProfile#1]
The current code does this:

```
DBI->visit_handles(sub { shift->{Profile} = $DBI::shared_profile });
```

But according to the DBI pod:

> If the execution of $coderef returns a true value then "visit_child_handles" is called on that child handle and passed the returned value as $info.

So if $DBI::shared_profile is undef, as it is after the profiler information is collected, then visit_handles will see the sub returned undef and won't go on to database and statement handles.

This fixes it:

```
diff --git a/lib/Plack/Middleware/Debug/DBIProfile.pm b/lib/Plack/Middleware/Debug/DBIProfile.pm
index d76bd86..a557c3e 100644
--- a/lib/Plack/Middleware/Debug/DBIProfile.pm
+++ b/lib/Plack/Middleware/Debug/DBIProfile.pm
@@ -73,7 +73,10 @@ sub _set_profile_on_all_dbi_handles {
         : undef;

     # for any existing handles
-    DBI->visit_handles(sub { shift->{Profile} = $DBI::shared_profile });
+    DBI->visit_handles(sub {
+        shift->{Profile} = $DBI::shared_profile;
+        return 1;
+    });

     return $DBI::shared_profile;
 }
```

**Comment by timbunce** [comment]
Thanks. Fixed in cad10d1 for 0.102 release.
